---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spegel
  namespace: argo-system
  # annotations:
  #   argocd.argoproj.io/sync-wave: '0'
spec:
  project: default
  sources:
    - repoURL: ghcr.io/spegel-org/helm-charts
      chart: spegel
      targetRevision: 0.3.0
      helm:
        releaseName: spegel
        valueFiles:
          - $repo/kubernetes/apps/kube-system/spegel/values.yaml
    - repoURL: "https://github.com/wouterbouvy/home-ops.git"
      path: kubernetes/apps/kube-system/spegel
      targetRevision: main
      ref: repo
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true

