---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  namespace: argo-system
  # annotations:
  #   argocd.argoproj.io/sync-wave: '0'
spec:
  project: default
  sources:
    - repoURL: ghcr.io/coredns/charts
      chart: coredns
      targetRevision: 1.43.0
      helm:
        releaseName: coredns
        valueFiles:
          - $repo/kubernetes/apps/kube-system/coredns/values.yaml
    - repoURL: "https://github.com/wouterbouvy/home-ops.git"
      path: kubernetes/apps/kube-system/coredns
      targetRevision: master
      ref: repo
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true

