---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argo-system
  # annotations:
  #   argocd.argoproj.io/sync-wave: '0'
spec:
  project: default
  sources:
    # - repoURL: "https://github.com/ajaykumar4/home-lab.git"
    #   path: kubernetes/apps/argo-system/argo-cd
    #   targetRevision: main
    #   ref: repo
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.18.2 
      helm:
        releaseName: cert-manager
      #   valueFiles:
      #     - $repo/kubernetes/apps/argo-system/argo-cd/values.yaml
      #     - $repo/kubernetes/apps/argo-system/argo-cd/values.sops.yaml
  destination:
    name: in-cluster
    namespace: argo-system
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true