[env]
OMNICONFIG = "{{config_root}}/omniconfig"
KUBECONFIG = "{{config_root}}/kubeconfig"
TALOSCONFIG = "{{config_root}}/talosconfig"

[tools]
"aqua:siderolabs/talos" = "1.10.5"
"aqua:siderolabs/omni/omnictl" = "0.52.0"
"aqua:kubernetes/kubectl" = "1.33.2"
"aqua:helmfile/helmfile" = "1.1.3"
"aqua:cilium/cilium-cli" = "0.18.5"
"aqua:jqlang/jq" = "1.8.1"

[tasks.omni-bootstrap]
description = 'Bootstrap cluster'
run = [
    "until kubectl --kubeconfig $KUBECONFIG wait --for=condition=Ready=False nodes --all --timeout=600s; do sleep 10; done",
    "helmfile --kubeconfig $KUBECONFIG --file {{config_root}}/kubernetes/bootstrap/helmfile.yaml apply --skip-diff-on-install --suppress-diff"
]
dir = "kubernetes/bootstrap/talos"
depends = ["omni-sync"]

[tasks.omni-sync]
description = 'Sync cluster'
run = [
    "omnictl cluster template validate -f omni-home-ops.yaml",
    "omnictl cluster template sync -f omni-home-ops.yaml",
    "omnictl talosconfig --merge=false --force $TALOSCONFIG",
    "omnictl kubeconfig -c home-ops --service-account --user ci-user --merge=false --force $KUBECONFIG"
]
dir = "kubernetes/bootstrap/talos"

[tasks.omni-reset]
description = 'Reset cluster'
run = "omnictl cluster template delete -f omni-home-ops.yaml"
dir = "kubernetes/bootstrap/talos"