---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1nxcj78klmmh6uxf40musqmvmfayjpfv2sassjcrt22rtjsa4xd3svvtlxn"
  - path_regex: infrastructure/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1nxcj78klmmh6uxf40musqmvmfayjpfv2sassjcrt22rtjsa4xd3svvtlxn"
