---
version: "3"

vars:
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"

env:
  KUBECONFIG: "{{.ROOT_DIR}}/kubeconfig"
  SOPS_AGE_KEY_FILE: "{{.ROOT_DIR}}/age.key"
  K8S_AUTH_KUBECONFIG: "{{.ROOT_DIR}}/kubeconfig"

includes:
  brew: .taskfiles/BrewTasks.yaml
  cluster:
    aliases: [c]
    taskfile: .taskfiles/ClusterTasks.yaml
  talos:
     aliases: [t]
     taskfile: .taskfiles/TalosTasks.yaml

tasks:
  default:
    cmds:
      - task -l
    silent: true





