machine:
  install:
    disk: /dev/sdb
  network:
    interfaces:
      - interface: eth0
        mtu: 1500
        dhcp: true
        vip:
          ip: 10.0.88.10
cluster:
  allowSchedulingOnControlPlanes: true
