ansible_become_pass: ENC[AES256_GCM,data:wababUU=,iv:gjklT3KmmV66bSb0Ljsdpltcl5wYAkTdKBqrtLirmj0=,tag:QemGQXl6m2N8+4qaDQ0wmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nxcj78klmmh6uxf40musqmvmfayjpfv2sassjcrt22rtjsa4xd3svvtlxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Z2NHN0EwWmNRY1JHWmJB
            YTlUWUI4NkRTdmxsSTAxbVBQUUdaK1FDSVVNCjNHWjlhTWc1UExCQkszdS9xUVJN
            eG03dGtYeHcranpXT2o0TkJxTjRVWnMKLS0tIGkzY21JSWl0Nm0rMzdaNW5nUmdX
            TEIrbjYyZ2RSTU1iMERWZXptRGdNUFEKsgXG43pA7cJNB/EnMhS5rp6sTHaUX8Qc
            J5+OqVn3WLArFsY5HCBjNjm6JegyMTecSuINeWY1GjGW6fySULmpoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-02T14:04:57Z"
    mac: ENC[AES256_GCM,data:RoE5uN5RnQqxoQoIkYkvRCLf4eU7M6/XEqFf9Lqhyz35oZBkc0eRbEWk6SwXZ03MbMJaTbCR/UZgHotPKHZvLxngHAsuYr8vqvrkX5c0LqFpmNoAJkXOujMuEx5pQy39m2iohaRZbs+w6x1CkOjEWoY8GtRPyVOPF71b5oQyvIQ=,iv:hIqaP1FtY+v9rRYmldrBwtsv3jDpAUirOXrBgfdSQM4=,tag:QqOiAqnFdQA6A2F6XfH3Bw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
