ansible_become_pass: ENC[AES256_GCM,data:yrImBx8=,iv:4gY0qy6NqDIByhZVsyxvykDyBgwGCusIjnhzczzgXPs=,tag:NkhRFSDjWtBJw68HJGG8xQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nxcj78klmmh6uxf40musqmvmfayjpfv2sassjcrt22rtjsa4xd3svvtlxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRnFRWFFVY2YzYkM1dk9w
            U3FjSitlUVFIK2VGSW9XY2ZoTDAvcXdibVJnCjRWNnV4M3VSdjJqVXBneExJR3FZ
            R0VPTmh4OWRJeVlkUmxhSUJFendVS28KLS0tIFpJL2tmUXlrYWRTVzl2Rm1UTzQy
            K0RXUGdkN0FvNWhNbFdCS2VsbUt4SFUKwE5sKVyiM4do25fED+zXBOI3SBDZv3OZ
            U4gx2pmPrSC8Ls5Uiv+LdPEshvkyhQmdYkbFXngXUNgdxHCwzpY1Fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-02T15:02:19Z"
    mac: ENC[AES256_GCM,data:RzF3owwYhgYfWZiuY21pdigN6+Bwtu1kuzRAdEAv6Dup9Pu3eIPCZ+ZGzlJxMuF33+MwO1vApQtzi2XVPYyt6Cf19JLocudMqB7D9q5ojh+19bZQD426bDAcwdAPENOuCuhwF49dCmQb/uQ3dgiMwVOCWRmx2zcRaeS6MYrt+Q0=,iv:HpLghjyPzPwqOBaQggfcdUFYJ24n4R2sUXc50cnEHrg=,tag:WO2GlZztkoKfqhsch31Sxg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
