---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  destination:
    name: in-cluster
    namespace: monitoring
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: alloy
      targetRevision: 1.11.0
      helm:
        releaseName: alloy
        valueFiles:
          - $repo/kubernetes/apps/monitoring/alloy/values.yaml
    - repoURL: "https://github.com/wouterbouvy/home-ops.git"
      targetRevision: main
      ref: repo
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - SkipDryRunOnMissingResource=true
