apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../common
  - longhorn.yaml
  - cloudnative-pg.yaml
  - postgres.yaml
  - authentik.yaml
  - metrics-server.yaml
  - kube-prometheus-stack.yaml
  - loki.yaml
  - alloy.yaml
  - headlamp.yaml
  - cloudflare-tunnel.yaml
