---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    name: in-cluster
    namespace: kube-system
  sources:
    - repoURL: https://kubernetes-sigs.github.io/metrics-server/
      chart: metrics-server
      targetRevision: 3.13.1
      helm:
        releaseName: metrics-server
        valueFiles:
          - $repo/kubernetes/apps/kube-system/metrics-server/values.yaml
    - repoURL: "https://github.com/wouterbouvy/home-ops.git"
      targetRevision: cursor/p2-observability-netpol
      ref: repo
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
