#example: https://github.com/budimanjojo/talhelper/raw/master/example/talconfig.yaml
clusterName: talos-dev
talosVersion: v1.6.2
kubernetesVersion: v1.29.1
endpoint: https://talos-dev-api.im25.nl:6443
domain: cluster.local
allowSchedulingOnMasters: true
allowSchedulingOnControlPlanes: true
clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.245.0.0/16
additionalApiServerCertSans: &sans
  - "10.0.88.10"
  - 127.0.0.1 # KubePrism
additionalMachineCertSans: *sans
cniConfig:
  name: none
patches:
    - |-
      cluster:
        proxy:
          disabled: true
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:admin
            allowedKubernetesNamespaces:
              - system-upgrade
    - &kubeletPatch |-
      machine:
        kubelet:
          nodeIP:
            validSubnets:
              - "10.0.88.0/24"
    - &containerdPatch |-
      machine:
        files:
          - op: create
            path: /etc/cri/conf.d/20-customization.part
            content: |-
              [plugins."io.containerd.grpc.v1.cri"]
                enable_unprivileged_ports = true
                enable_unprivileged_icmp = true
              [plugins."io.containerd.grpc.v1.cri".containerd]
                discard_unpacked_layers = false
              [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
                discard_unpacked_layers = false
    - |-
      cluster:
        controllerManager:
          extraArgs:
            bind-address: 0.0.0.0
        scheduler:
          extraArgs:
            bind-address: 0.0.0.0
    - "@./../patches/metrics.yaml"
    - "@./../patches/tpm-disk-encryption.yaml"
    - "@./../patches/harbor-registries.yaml"
    - "@./../patches/longhorn-mount.yaml"
nodes:
  - hostname: talos-dev-1
    ipAddress: 10.0.88.1
    installDisk: /dev/nvme0n1
    talosImageURL: factory.talos.dev/installer-secureboot/ebdfa27a8d6272acf806ac6a5c968c3c284a47ce880273cecb19442c11bf0474
    controlPlane: true
    disableSearchDomain: true
    nameservers:
      - 10.0.10.2
      - 10.0.10.3
    networkInterfaces:
      - interface: bond0
        dhcp: true
        bond:
          mode: 802.3ad
          lacpRate: fast
          xmitHashPolicy: layer3+4
          miimon: 100
          updelay: 200
          downdelay: 200
          interfaces:
            - eno1
            - enp2s0
  - hostname: talos-dev-2
    ipAddress: 10.0.88.2
    installDisk: /dev/nvme0n1
    talosImageURL: factory.talos.dev/installer-secureboot/ebdfa27a8d6272acf806ac6a5c968c3c284a47ce880273cecb19442c11bf0474
    controlPlane: true
    disableSearchDomain: true
    networkInterfaces:
      - interface: bond0
        dhcp: true
        bond:
          mode: 802.3ad
          lacpRate: fast
          xmitHashPolicy: layer3+4
          miimon: 100
          updelay: 200
          downdelay: 200
          interfaces:
            - eno1
            - enp2s0
  - hostname: talos-dev-3
    ipAddress: 10.0.88.3
    installDisk: /dev/nvme0n1
    talosImageURL: factory.talos.dev/installer-secureboot/ebdfa27a8d6272acf806ac6a5c968c3c284a47ce880273cecb19442c11bf0474
    controlPlane: true
    disableSearchDomain: true
    networkInterfaces:
      - interface: bond0
        dhcp: true
        bond:
          mode: 802.3ad
          lacpRate: fast
          xmitHashPolicy: layer3+4
          miimon: 100
          updelay: 200
          downdelay: 200
          interfaces:
            - eno1
            - enp2s0
controlPlane:
  patches:
    # - "@./../patches/admissioncontroller-exemptions.yaml"
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl
