apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:T/EhDXtvuhwfhtJhDAaf3/a7mc2CLhX6k5240HszjWlrjS5i,iv:0iEVfvE9lzoeiHBWh83VbL2rTO9pLNgbUA5vuwGkQmo=,tag:OHl3z81Z6qaI32kDrOHfHA==,type:str]
    credentials.json: ENC[AES256_GCM,data:zsKIuNrVKKayWJY0YuacJHGBiNCuwHU1JKhs3aLwKc+6EH9VmYMmc+X8hrm8FiMdOfqUMqGH0p36KfUOhUolg1/58Kob+A+jE1hmOrbsvA/zPm0zFYC75SnYGrfcoYt0uZwl78K6BCRMlaANbN21e2BNEBHv7ZBkqIqKlHR/fXXle2RG5N8TK20LWQMgKzEigo30ryQcFSieQgYGD8gwug66Lj8HG/qyQRjuPh00QA==,iv:beKcATcmmBROTjcBJvFdbHDnwOAAT8ta1jfLJa5KRYQ=,tag:SO9u90suV2ePiz/Nc9YJWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qy5yxmh6g3pg92vjdgd6f3prrdvktsf0szcvjrqmc37nac35tapq8v2r00
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OHNmL1RPTnZEank2dmZz
            dUU1RnM2TCtoUHB5WUMvb0dPM0VZVU1LcERZCmFtV0FyOHBJbU9iRWdodkRDOXJH
            cDRYMlB1S21ZdUJvK1RjSlpIQ09BUFEKLS0tIGtEQVNWbnpYOHVSOVIxNWVTc1Y2
            UWhZdWtCQ29KUkVtSWFyL0ZrQXJVWUUKuAWDOE3+YwNdV4Oo33++Sno1PBENskBR
            4LO+heheMs7gJzULBTDP844qwjCjtg4UkbJuMt1nCv4WvkLsVcUYkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-14T11:08:47Z"
    mac: ENC[AES256_GCM,data:so4qMTs5WefWvvxxI9Cwp5Qtj6kCf7QyEP9JGmpgBR9ZoSn1SE41D0D7QPs/1XudqtOzG7F5zQs975W326sKSIIp3Am6VUXtlmMi5GAE68Kefc+BO4rBVqyQBUiGfrZKgrF8Ox2HAgVFGHzHvyk7jZHgwlke5ylt6EE3TfSnRY8=,iv:FBMMRyqTRS/4K/6giJd9VF1su2++o4awD6H2TnATvOs=,tag:LvVCb0XWe4Kv9Ok7wKFhHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
