apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:qvgRdTKUCQQ=,iv:+5Nu8zZUO5fcSRSKIjh46gAGZHzY7bdGOgfY7S01I6Y=,tag:fiLTWLi1fNvtAoeTZ2XGfw==,type:str]
    admin-user: ENC[AES256_GCM,data:i3Gfx8Y=,iv:9tOpVZeW5J1eUYKIzcj8nmhhxUjlW9jIaoqvoQ2DfOk=,tag:Eg9C9R0X7MYCmFWBzrcjNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nxcj78klmmh6uxf40musqmvmfayjpfv2sassjcrt22rtjsa4xd3svvtlxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMVZZMGNwcDh5VjhMNEFv
            RzhHa3czZm1UL29USGRCSm1LMzBiaEMvaVRJCjRidm1mUWoyeTJrRW9MMjArZzlj
            b2tTbWZ2Vm5aazk3N2xnYjhEN2tRWVkKLS0tIHFMb2wwNWNQNnh4ZVJsSnYzTytm
            NWhxeDJFSEVEckowRzdnbklRNy9XNU0KI3X2rn1Z2MKaTfiLcs/a6O8PXut1t/iV
            K/yIDoht7RhUE3VWz7dGR2HBjeGHP33jMjExFjOcqU+r6HZsaE5IyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-02T14:05:37Z"
    mac: ENC[AES256_GCM,data:u6gVanbMBBIPbGbjoq7YOSFBYGqHWGcmbJgrQaKPCVWiIcTBMuHCV2V3inu7Ie6RRoM2aUjvky3Xl56/xKAkrQoFFRyqcv5jur0jxo6FMXrQaAWaFNyKp4rafYEFujD2+/ewb3zhBNZ5GZz/8UlQ9+URTwMRyWb0Wl4J2ZyZXuo=,iv:ruWPydd5VWWWTG2ssNrqRECC0wULfMUJ/Ow5vrYLzVA=,tag:2fbKmPef8k0p13F5UWr81g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
