apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:ly1HubUqamQ=,iv:fVlTeBhSuRHFkgEIj1kE1HWF6Ypne22wmLJCjU4x0G0=,tag:h8VKX68roNqHPRxa1oLt0g==,type:str]
    admin-user: ENC[AES256_GCM,data:80JPT54=,iv:+nddORAO1nLMETqSPfif5wWwlGvRgG5mlzee89MhiQQ=,tag:iW2fNEQZkxHk27iu8LdrWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nxcj78klmmh6uxf40musqmvmfayjpfv2sassjcrt22rtjsa4xd3svvtlxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MUdsS1kxYTJyNStWKzdG
            dGc2K2pNTDkrNTZWRDFLTFpwQjNHWXZibWpvCnByb0pxamxLdlZhSUkyNE8zdzJB
            dGNxSzVhcDRzdEVkZDBUaWwrU283ZlkKLS0tIG0xY0djbkhNZE9ZOTM1TGk4ekdv
            WFdhb04xd2J6VnpUcnVhbWFDNzV4NlEKQa87PoMCn0pZoaf3mRsyidi2pxjgWafN
            MBUokP4OlcPhC3LU/1b5XLT4i+rmFHUiznVjsME+DywV3R3ZPjhDnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-02T15:03:03Z"
    mac: ENC[AES256_GCM,data:abm0ZGHRGLKorAaas6iBEV+ihWGcvlVdcuES7//l4aqcH2+kTh5FbMAySQYEC83PeQhKjhjNzpunWShhX/qXnPj9UZsW3hDsTFEBj/b4k8ManOeUuncMQmGId2+tdAvRpAgDWylfyHx8oQwk1potttztw6iyBbSNRgo5s+6Pu6I=,iv:R8QkuBt3BjJEYXPuf/KqzakbBuuUTWBhdU9e1LYGAnk=,tag:ZGv2RFP5kdzwJZPKC/R21A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
