apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:mNFyq83Jbyg=,iv:ysW7w/RqT87QMdKtKy1G47sLTZC9cpGegnm2WBrhUWs=,tag:BOo5kvEBw6Lvg0weNwPPKQ==,type:str]
    admin-user: ENC[AES256_GCM,data:IN5vnFk=,iv:o4u3+V1Z9gjxjQGPGe3epBmVCv/lTG95OMQRpOoR4m4=,tag:c97/cvODIe1PabMmkAehJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nxcj78klmmh6uxf40musqmvmfayjpfv2sassjcrt22rtjsa4xd3svvtlxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMS1pxYXlmZmFEU2hLY25a
            YjNHcnJzY1Q1K1B0T2lmU3RpVjl6WllrdnpZClVmT3Y1dWZ6NG04Mno4ekt5V3Zz
            MHVVZ3R6ZzhCQm56Nk5jSjhLMWQwNGsKLS0tIGJMeVZNVGdHNTFpa1g3alhFSmZk
            VjNhTUNjblZWZzdnMWtiQzZoelloVE0KEIftxq4FGNfbkz6hX9eyqo/AzKRNjKcP
            5wudxXM0HjeC/LLIUobrCW4z7v96Bc3gF45XVZyUVUcrgYh1VWgRVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-31T09:42:45Z"
    mac: ENC[AES256_GCM,data:cXdby143o2TQ1U0JFh1RAnEB07qNWOwYZ/t4OWgnCuiOZreGRElIDXzBEFeBYjwzjiZZ2mVrQ27C2lEZ912iKwZzTm9BkLksoVr3OKXZTC9lqrIS0NzpngaMpReeT6T8DchKsV9TJAAi+qiyJpw8FUhFP6+YAjJgsx6LNHWYIBE=,iv:S2NO8bD/Y2+yRAnYXyq01L3lhxxLJknQH/652nTkbJs=,tag:0SH/hcZCkW3fzGHR4FP1/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
