apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:fUYLYdWE2rzSpM8qHS0/8UXV1ByUxkNS,iv:I156p0Hjhx5jDVmzXmwKZx5ck1SmyZcGCIEQVmAMDi0=,tag:bTvDsDGAKZX8+v6YqAVPCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nxcj78klmmh6uxf40musqmvmfayjpfv2sassjcrt22rtjsa4xd3svvtlxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYlR0d2JWSFIyZVBlcEpj
            ZTZFRGZJWCtmTkxnQUwySmw5M1kxZk5EVlM0ClJBQ292Vkl4KzdEcEhsbGZoYWFE
            amdkbUdNblRGWUhuSENuWG9acjNjWlkKLS0tIDBWUDU3RnVDSU5zY3hYSGg2MlhQ
            eUFDY2ZnTEJSY0hvVEhaRGRFTzVwZmsKlWT0ZGxkeZIDYjDCN+aqLKiBLpoyZFgK
            0z97vcu5oJKLawXG4vXkyCcwvZOwT6Uw88CqIGxnpB6ZFBcKuPJkUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-02T15:03:00Z"
    mac: ENC[AES256_GCM,data:XVmrY6rhBrNL1xHcWfNc1QITCcFXuf1HdmOK+pE2twOqJUa1RZqo7Z22duAYoWR75xFGe8WFMFp7cD8XG+nG05EY9qzlAm/Ex199+cI1Kry7IG3jBqUT1GkTMlsT4Kr12AZ4O+kXYUDyjwf+WpA4uEdI0P6HARk8QHFjOVdHtKU=,iv:vn7FhBb6L64CVhS5t0S2D2TjCrgAsWVtlcVBJZ14DCM=,tag:rzPOfc4IJFoofdlxxabP4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
