apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:7r/7Nm329gG/iKxxuo5/tc3yZG73jfoe,iv:YrekrCsQjUVTMfCZW/8e+h/we2UWtueYBptADAqJqVU=,tag:IpLs7lTfosAQMBIp0hvwhA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nxcj78klmmh6uxf40musqmvmfayjpfv2sassjcrt22rtjsa4xd3svvtlxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWTd6VFJLZzZ4M0s2K1RC
            NVNsUVNRY25YZUdBTUZ0Q1NRMDk2eUpwS0Y4CmxrKzFra2wyc2dNeER6VW5mTU51
            aFdpcU5pY1g5YnJHV0tlT3VjTEZtazAKLS0tIFZUQ3ZQcVA0M3F1cE1FWE52KzJL
            eFh0Mk0vWThjNGRWT2pEdVpFaFBnVEEK17UVhniR76s4DWLssfbN0utYMIC/AeaJ
            zBzHrBshstEymVA8gYWoN1ppQfrjLI3tCJlMEaQb4ww+uNuiZE1erA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-02T14:05:34Z"
    mac: ENC[AES256_GCM,data:lrnidhoXRxZM823eoMztif6HzQGI+Hcu8GtIZBr9al8HgZZzPoTp06DgMHw0t5/g24BYLZDqOHCpSm7Az4COgN/bKTsYl+yzy7eaaEl5oMhG6DrkU0KevFr2e9l1H+kyarzTGTcBTpEriNI56O44Lw/JwJa/Se+EQkpkbCecRzE=,iv:5t6u8caOs6XaRPgerfKHGY5sFRqgi7aXAWohuH5K8us=,tag:NA3wfvSV71ei/PZK0FdaAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
