apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:lurelVcfKu6F77Yp8/vxqYQfsf7jbeAI,iv:i6t5CJna0+zr27VJn0uz2iuDuhsWOIf9JqIcYB8al5U=,tag:BoyNtWgUIysanI3uG4prug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nxcj78klmmh6uxf40musqmvmfayjpfv2sassjcrt22rtjsa4xd3svvtlxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnanB4YUFqT1BVVUFMUlZM
            TmNUNkN3S25WeGVJeDNHelhaZTZNNVdKa0NnClNidEFTMWh3MktVdDZLdWdGMmNt
            dSs3dm9mNjRJY3lDMzhrUjVMUWpuTUEKLS0tIGJxdTR6Q3FTQVVzcjZHMmh0K1Q1
            VDZyRXVhQUZ6YkZUaWI2N3huL21Xd0EKdKXb8yww+VaONtwbd0Pbdk2qI+zFl8gL
            2A/+xPywpbFZ1lOE0ndTFCimrBjp/RTzrX3thgYQ2Och5bA/juJENg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-31T09:42:42Z"
    mac: ENC[AES256_GCM,data:UwnHk5WPAzE1gXJDZ7VV9SC4Bv/BI3MkvBffBdP1Ye2Ch90fuZ8NOz1pNeeeLA9B7rMlkriaamla7lqj6MUTT4HqDfQMreJPr9R7Uf8TgmEPsLXxJ4SR16hB4UuTpV5AjfZNNTl7HwlnGaPgzEDP5rSNfKCZXppsHTH7dRREDMs=,iv:zwZqlYe4xOtGIeJHcbcz+R9P8566UIYWnxdoZ8VQjUo=,tag:Be65YKqm2yPnDE3EV27DxQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
