---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: grafana-oidc
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client_secret: "{{ .GRAFANA_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: authentik
