cluster:
  apiServer:
    admissionControl:
      - name: PodSecurity
        configuration:
          exemptions:
            namespaces:
              - monitoring
              - longhorn-system
              - system-upgrade
