apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:0aO9R+MLmdVQoJSOFZmyp9PgFc4ptuRoeIx7nuGDX2+Fg+LEvL38fg==,iv:NtUHuRxo7pfWTWuCp6tBqGh29UakpyoWm3WKj7uWSJ0=,tag:YDGFVPtoyAWG29AlXJVUeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nxcj78klmmh6uxf40musqmvmfayjpfv2sassjcrt22rtjsa4xd3svvtlxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpemlMaURySC9hd1R1cEdM
            eEJxNUNHcmtxZ21OaUp0OXIvRGh2NGJxa0ZVCll5RXlacnh5K2I5RDQyQklWVkhV
            cC91dnJXZGV2MnBQaDFpT1FFREdKU00KLS0tIFhEbHJ4UGRLSDFmanErWTlLd3Y3
            TkJPUlBZcHNEZnF5a3AyVlVmakt5dGMK3GzMxcCo4N/nE6pBxckUw3awHioc3SMz
            PjeRHQxSCmiy0o0BQEN3Djg04qcWWzH0t96aUqn3whxATE41aSfcwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-02T15:03:00Z"
    mac: ENC[AES256_GCM,data:j0XaaqsnFrKJvzr97Ff3/6ir8ajdeGXkPwxXvmCIRC5iMRCoILv0iCXbMT/yHPbGw2O5jej7Yzc6kZVS4AeRzfRmS3d4BoV1Lqhguwoch5aXSz9OtcaENdlKZ0JWvNhKoAqXdOUjh68jCICt07eNp0yJk9jFG1M2psIDGI6pnHI=,iv:/OOUGUZhzvwbmj2wNvZEM9zzaYgyCCDVkyuSHWueV8A=,tag:XgfuyHrO0oG9cmtnqczeew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
