apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:ZjE1X672/mvQpp++Wc5NDPJfKyTy9ndJSnpkvlOVEHB1LWCBRePy2w==,iv:Y3+wEMZHafPqatGrB2BkcsSx1906I5UuQRDYzx0aJG0=,tag:zWeNvHhPx+3onCXmobz8EQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nxcj78klmmh6uxf40musqmvmfayjpfv2sassjcrt22rtjsa4xd3svvtlxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOGZYZE1ZWlBDRXdER1Ir
            aG8rbkdxZnNhOTE0Y3ZGakZ0S2dabXVETVVvCnFEZkJab3dDV1hFaHpUd01WQ2xn
            cU54L3NqT1VpdFFkZGRqT1hNMXRPZW8KLS0tIHNpSk9nWTRwQ2xFcEVBQUcvMDFk
            US9TZEdzeVNaTEsrWGJYTklPeGJSRmMK3Iih44JgVjo7IcFCslzwvnkh2xg8wtyy
            qX/GfpUdU1dC6XVieo57hMhaJGf0bskbce+PkLckJUFvM9ZTDJ3DJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-31T09:42:43Z"
    mac: ENC[AES256_GCM,data:9ATcQY4sAQl+lVbYokJq7WnxRHrb30JNFa+aiMJb4DbDUhccWF9dxl0HXTShCbH7sO8hKffB6t+RFKSzwIz1MweUDOht2wyMXB2iHdwAS9hlVEt031wFdrJBcOB1K+qZIRc6Nf/r31r5hGAD2jkm0n5azPXfWfThGGQ5QEpntLU=,iv:+Vx28nh1OfgonBFLw1mnhMQ6hnQNru0bqHts5ieg5bg=,tag:l9fdksey7f2iECkG4tAxBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
