apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:ZxwCnaTu/GpKmcWwFhDYHrWxLkQzFhITJeBPTDB4jhyj7VbwOR8qFg==,iv:T/TzLCLXjA34+C4djdADrUpr0bl5asUmM52/TFyUZco=,tag:Xfo95kddnZ7at6w8zEFaZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nxcj78klmmh6uxf40musqmvmfayjpfv2sassjcrt22rtjsa4xd3svvtlxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWaHdqMFNWQXkrMlpJQmw3
            azN5Vk9SNC9OSENCV3I1SG01dEtVcEtSazNFCklzcVViYjRSUHJuVXdUd3d2NW9u
            R2I1SSt0OUpEVEE5Y1VzZkkwOC9pYncKLS0tIG80SE9zMFlWeTZxdXpTankzNDBh
            SnJqbEtjeXJDc0luN2M4Z0RHV2JLZ1kK4uZRKj/iXgjWEt0FhETkbmLbieqWscQp
            PTET9GggXnuESaghNTgWdpIphhKkwTnlFMcV8SQ+P7WM9WX80Il2qQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-02T14:05:34Z"
    mac: ENC[AES256_GCM,data:tgFvqGvI9ggoZdZb+PidhxFMIYrYgCbIxqYGfeyijuT2TRLpcn/3VpPwJB2E0hMN0j26+v6iLPkBr8Hhk/YGLWyWw4bsYIUTEyFgZM7wffITQ3hqL/IX9y3ie4XcRlRzw1YRzfjOJJoCBECORWz91aCU7N5qa7ji/V4v2b2wEvI=,iv:7CGQbW6SvlsFb+kvf2u3Vp6TqiXiq2K3thFnPqmJLlM=,tag:ffTcSRaXpszufkmU0nFf0w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
