apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:RbqBm0pdNiTrS7sHP5u/2jhX49+qX8C6bcN+J0B/38hthCTJ8ePMJw==,iv:6lAXhPFfTO7hnpdLNIeyKB3vFsJ/GQCxBUF1m2nbwMo=,tag:oA+5fRTKxAzwequ5Q9fVFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nxcj78klmmh6uxf40musqmvmfayjpfv2sassjcrt22rtjsa4xd3svvtlxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTWRLLzdQcE55TlF3ckZM
            cEthcWR2MVkvd3FlTzdHZWhad1NMUHpZNzJjCkRtWTcrVDZJdG5zcm0rNkx5Smhx
            ZlQ2RWR4b3E1V2JwcE92OFp5U3cvL2cKLS0tIENsR3lpTk1yT3NCaHRKdDRyMWhZ
            dDN1dFBkWE1tT29IYmVnRmRLRThDUVkKcpJlIatdI8dRM4onAO2Q+znvoqL46ot+
            LHHjdzfghXDgbTZ5pWJTkuW1vXyYs5lz9HC+MpUacUS+nNWvNeuxDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-31T09:42:42Z"
    mac: ENC[AES256_GCM,data:MEjzfLaLUK7IYQG3fc0ZmeXxG/xnEWbVHFWHzKBTypln+GC+aeJJRqYElcIb7CXq2On/a6GgFXrEqw4A6JfoVrsgRI695MX7fj0v2t+cF28OGcBGbZBEQW2vU4vmkNVzMGn8FIY42H+0HenEs2jrG27akAyr4pEqtUZIJk219k0=,iv:5xjqPR747Q5mtivHrDEklhPmVEA+YeOFdle87wKFkWg=,tag:wrUSyWLhwR5+T+tmTBrFbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
