apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:0IL8+oh+kk0lg/OcoZWm0Uy1e2GiaOQXrLJR2lyy6B1mhU1DrMod6g==,iv:RCg7aZcRb3VrSsR6NGIrwmxDSitvuTnDCCwBdy6IhNo=,tag:mXdax52fUjtttnpDyBHuzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nxcj78klmmh6uxf40musqmvmfayjpfv2sassjcrt22rtjsa4xd3svvtlxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VGszM2V3TGxZa2hYUlh4
            ZFBWOE1UT1Fld3pmOTVMNDU5NnJTQ0l3TlRRCnlXOHVpUXQxaDdrejd1VnpVZWFV
            L2ZCVytuMjR0a0M4N1RTK1lnME55MmMKLS0tIDVrV243ckx6NkdHRFNQR0pwR2g2
            Z0lZRU1yUXlHb2UxMGJCOStDT0dSdW8KZf1nxFr2CnoO2WLQ4dz/YqlF9GYcCmhg
            Oaq3KnugKBDr4lu4l0OFGbuhmPwugLH/ilitz2LWLQ1V+FBvrg73nQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-02T15:03:00Z"
    mac: ENC[AES256_GCM,data:YbqjG/pe8VU3Y6st8jA+gK+pTff/x1+rWFgngBq5dSi33EVl/KqPLI2BSw6b15AaUT7Bo39zLJNLCNPAu+Hm4q5ugcdD+OFrq5S8Mipq9P7FFhvF8AxSS0CGb1D011ctSWfNEsquaCjfjEh91cgH82w+vq+CDIIe/KqHI22PzFE=,iv:XUvw2tfiGmBA0DTUBdoTpp402Wp2/vt8A0pmxe03Jq4=,tag:vqtFwKttQl+vS+n1SGJBEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
