apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:gf2mFM7XV/g13q6oqOCCnXOCgv1Z1VDO3silS4R1s08LrpQEvaqttg==,iv:l3/GrJVy0q576y9tIbQM2K++KpVJS280pMaaZosKYDk=,tag:rD5vmv1efTdIXIQsVsLh3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nxcj78klmmh6uxf40musqmvmfayjpfv2sassjcrt22rtjsa4xd3svvtlxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WlJET3FOb0dLQkVZMHht
            UXl5N3o0aHd5aDJWdlVWMTQwQk9vMlZiaUE4CjNYUHZzYWduWnJMSHF2bmtjVkRW
            RlY5eU1XclprUjFSSWFlTi9NK0hBMWsKLS0tIEhKTllhR2RscEVnRXNSK2lrN0ZS
            Mi9VeFFpcXdpV1pWY2hDRUEzTFdTMlEK+y9CyQXoyiffZaIFtgs5QT5IY8yPeWne
            nvWJglMsqdKFhngrd9/XQuERwgTVljI1Mp87iBGZCI+1YqERXaGLfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-02T14:05:34Z"
    mac: ENC[AES256_GCM,data:yUq9rbjtFGip0hor0D/dI+lD6l6n+08ODQFj9B/0Tgb88rgbiOoMB9qoeEa/NP2jJOnSH4a2fjYPB5pTlaLxuyaOsbHO3/JKypO4tVtodlXXXWet1hQxerJ1eH2O+JycFgHJRbQ/fgJjHpPrn97Xy2TFZChfcDooMmm6SHOp3Tk=,iv:/fChE2biXzSeweUYakA7irttyrbBI+G3k6yYqHEiBpM=,tag:zGp3AcDto5E1GERiLvxPtA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
