apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./externalsecret.yaml
  - ./deployment.yaml
  - ./apply-job.yaml
configMapGenerator:
  - name: cloudflare-tunnel-ingress
    files:
      - ingress.yaml
  - name: cloudflare-tunnel-apply-script
    files:
      - cloudflare-tunnel-apply.sh
generatorOptions:
  disableNameSuffixHash: true
