---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: argocd-secret
    creationPolicy: Merge
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        oidc.authentik.clientSecret: "{{ .ARGOCD_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: authentik
