---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
  namespace: argo-system
spec:
  hostnames:
  - argocd.k5s.dev # Specify a valid domain to reach your application
  parentRefs:
  - name: external
    namespace: kube-system
  rules:
  - backendRefs:
    - name: argocd-server # Specify the service of the application
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /
status:
  parents: []