fullnameOverride: "argocd"
configs:
  params:
    server.insecure: true
    controller.diff.server.side: true

redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  replicas: 2

repoServer:
  replicas: 2

applicationSet:
  replicas: 2