---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
  namespace: argo-system
  # annotations:
  #   argocd.argoproj.io/sync-wave: '0'
  labels:
    argocd.argoproj.io/instance: argo
spec:
  project: default
  sources:
    # - repoURL: "https://github.com/ajaykumar4/home-lab.git"
    #   path: kubernetes/apps/argo-system/argo-cd
    #   targetRevision: main
    #   ref: repo
    - repoURL: ghcr.io/argoproj/argo-helm
      chart: argo-cd
      targetRevision: 8.2.4
      helm:
        releaseName: argo-cd
      #   valueFiles:
      #     - $repo/kubernetes/apps/argo-system/argo-cd/values.yaml
      #     - $repo/kubernetes/apps/argo-system/argo-cd/values.sops.yaml
  destination:
    name: in-cluster
    namespace: argo-system
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true