---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: 1password
spec:
  provider:
    onepasswordSDK:
      vault: k8s-secrets
      auth:
        serviceAccountSecretRef:
          name: 1password-token
          namespace: external-secrets
          key: token