---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fetch-from-onepassword
  namespace: external-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: 1password-test
    creationPolicy: Owner
  data:
    - secretKey: test-login-1
      remoteRef:
        key: foo/password