---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argo-system
  # annotations:
  #   argocd.argoproj.io/sync-wave: '0'
spec:
  project: default
  sources:
    - repoURL: https://helm.cilium.io
      chart: cilium
      targetRevision: 1.18.0
      helm:
        releaseName: cilium
        valueFiles:
          - $repo/kubernetes/apps/kube-system/cilium/values.yaml
    - repoURL: "https://github.com/wouterbouvy/home-ops.git"
      path: kubernetes/apps/kube-system/cilium
      targetRevision: master
      ref: repo
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      name: hubble-ca-cert
      jsonPointers:
      - /data/ca.crt
    - group: ""
      kind: Secret
      name: hubble-relay-client-certs
      jsonPointers:
      - /data/ca.crt
      - /data/tls.crt
      - /data/tls.key
    - group: ""
      kind: Secret
      name: hubble-server-certs
      jsonPointers:
      - /data/ca.crt
      - /data/tls.crt
      - /data/tls.key
