apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argo-system
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.9.1
      helm:
        valueFiles:
          - $repo/kubernetes/apps/longhorn-system/values.yaml
    - repoURL: "https://github.com/wouterbouvy/home-ops.git"
      path: kubernetes/apps/longhorn-system
      targetRevision: main
      ref: repo