apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.9.1
    helm:
      valuefiles:
        - app/helm/values.yaml