apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:+R9lE2zb9jRAD90bHwTq1X1Jt7wyD8T03yPN1/d5LwO3lodYu0IBIpSL2vGJdSMUm2UZtvtCbJviEPCX9N9kQXDiwqtvvFwNs+JfP1AfWYWV1mj216byEUNVd358tQ==,iv:9C9f3ERTXgYir7UJEd4JLqlvMQwTI/f5piQBMJtOf58=,tag:7RdyT3u9tE3t4szowrQvRA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:ljW87zawe//zfnI=,iv:4/slSIxsoyQBzBOmJMAsgo9kaOL+J5xfIc8Vzlgc9QQ=,tag:SeCwBrmgvZHMImnnJOz2Rw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:4vWF5QK54POAcV5INCuunA==,iv:jDGK47hUhVx8qLXfP/avgD9wIaeZBXSMlxPxixNL8lA=,tag:bwQ1TCPEeo6wBZQ9bOT4Xg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Cbe8WVTzVR7n69zUINpHsdcB3f8bkL9th7qSDk4rELjT4VAt,iv:PN3x5btAIO/OpA+/xV27pJMWJ3eU+S83PFadT5+jg6o=,tag:rBsKs5pbBDJ9NWMLQBcmOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qy5yxmh6g3pg92vjdgd6f3prrdvktsf0szcvjrqmc37nac35tapq8v2r00
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcGkxcW85WWpaUzNGMUI4
            SktPQ0poM1h4WURqaUdoa01MWFB1RktXelZzCmx0eDhUK0hnd2FZWVdRcXRLTFp2
            VVVHdkdZYUpLSDdydmJ4WHFlQ0xmME0KLS0tIDRyTElUUXZmR1E4dUJOWU5tN3Zl
            RWh3VkNnVmNiTjF4WU1yb2RnRFM0RjAKsfLnfPWubKNUHc353iDjLnNPynCvc8Cd
            A5Gncph7VEcuaXDTuT67t/i9zkMHVY/Uoml98w8JqMkP9S8EN9q+Mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-14T11:08:46Z"
    mac: ENC[AES256_GCM,data:vsQF9R+tazFs4WUtJUw++//beeLeKPkiU6ady7gIAdvva8dOLEqusiYFOo+Lwejmt69JBXSmdIz5DZr4jTSHop60d/mnsHYpd5u0PQENgKpCKzszny0zFv7AskPjOMTIHFOWwzoI701TJBiDzQu31pbw3DRWwowIc1Ungm0978Q=,iv:zLcWS5cKTyrgghA+Il2urSJMI5g433k/dO8F/blP0Io=,tag:/bqgeotb2k9nMb788iMXLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
