apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:8qTZlMiFDrXdTrVA,iv:4oCN8s3CF1Q6bA6t13hSeBTae4i+3+DveLv+PPLclzU=,tag:Hp15+dEmoB5X3AAHhqA0gg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nxcj78klmmh6uxf40musqmvmfayjpfv2sassjcrt22rtjsa4xd3svvtlxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdzgwaHNhZTZWNkNNUnJQ
            ZitUSDBQVXFlUzZQM3BnTVlta2xJMjg4bEVBCmpCYXhMOW1rQWI2OCtpM3Uzc2Ju
            YTFTTGxJaFdycndSWTlvdmF4bnVta1kKLS0tIHNiQ1B0MkRQWURicDg5M2hTYXpL
            SHJOa3RwcGF2NjJBWE1qZlpkL0FuME0Kxtvj6FGOC0NXgP29FP73Kx6wo+AOIB2T
            tTYA3vsCFE/B0AOAd9RxuxiIx/WyY2yDCL8OZ1+a6VSUbzYG0ZlHTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-31T09:42:42Z"
    mac: ENC[AES256_GCM,data:qPJjlwQIim0mQ4iqBRmyGNSMKCf4ZdL5T1B41/sjwgZfWQF2SF++LVKFWxOhL6H3Lk55YGFfoP8q6+Y5/0of8KJrvDYCVSH/XudioDjsEd/uhwtAMzgi6NS2sAxaG9tZL9qpmGR7BGAFUq9ZE+m7eEweHT36yvHH0pEnb5x97tw=,iv:IH0F4BBx62kv0r52bBslHfeT4h55nXifOYNOpVVjIeg=,tag:vMbntLhXoOCkMAbULFMGag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
