apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:MN0fMwIhSOZtn67p,iv:8dBjFZAbssdYImacG9d1TJcihkj2adLEci9XKKx+3hM=,tag:N+Samz+3q1GZ54D8cRTRog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nxcj78klmmh6uxf40musqmvmfayjpfv2sassjcrt22rtjsa4xd3svvtlxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYlMzL2YwcTR4anF4a1lt
            d2ZNb0s2ZVFtN3VBQVZWWGVsWlVNakcxSmxnCmtubDZXc281dkFBa3BCYUw3S0Zl
            V1JXdm5yYUhHR2lORmw3VVNRdUNXOWsKLS0tIGNESm91d29NUTBGM2Y1c0Zlb1ls
            cnp4emRFNnU0NnJad1YxTjJETmdObjgKRsrMgJGk6alwgvLU9n0b6RcRaIK2io0e
            fWFF1kActTRhR+tsQqDujXGd1DVdBQFBNfK1tRuT33oKA0lA+1D3Hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-02T15:02:59Z"
    mac: ENC[AES256_GCM,data:D06zsl9aFa74NpLP9biASzkpikS0KEHxe0sLxzCVDJ1EDyglRuMcr2xEeL1n3Gd+BiPZIdx3UBfZPXItRQkzAumpZr1G7nFrKyhoiRP+KgJPzyjo2kKRva1/5RfDgMdK6iJShVEqO3KwgXM7OctF1/k/qg0oKRzHktNv1KzSC8g=,iv:J+XevIqlTypGGsYb1w/Cg6JGTE5EWX7aGpLnTbKrREI=,tag:YN8FCEH3lrC8ws6wh0neIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
