apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:3DZG6G37ITHosgnX1+Gg7Q==,iv:Eiw+YgnbHvjckZzZMD/cITd2npvQOrDuVPmEn0fAkD8=,tag:PHUNAK+GqglFSnqlJguykg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:1UhmwFx2htLaAGLNblrtkdhqokQNBeV4P7+9yoPfPAbzVqh0,iv:n3hgmCEYtByIbRSXo8HXC420mjWPalMq4Atw5k/b4IA=,tag:BcPXO3V81ef2q1Y9UWQ0rA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:Wdj0eUxD4UVyJzJFGS0=,iv:oNRQhnhBQO/59nF4DfzBctaZuA7zmTSvtjeOceIIqGg=,tag:oysGbpTYRVNix7mmsHlDlg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nxcj78klmmh6uxf40musqmvmfayjpfv2sassjcrt22rtjsa4xd3svvtlxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWnB0eDJITXEzMy9kTDBY
            ZlJuR055ZHMrU0pUdWxJNkpuL1hVSHhHR0VrCi9CeDAyMG5OVG9Mb2NJcFVFQXJn
            QWk0V0NHa1lqL0xJaWZDVitQbVA0eW8KLS0tIGV0OXp4UUhSWlRNU3BZVS9xTTFU
            WElxUnExUGpBT29TSW1WS1FDZHg0aUkK1S09h/5vIRLFhJXlD0g/dB7gxXuY/uUp
            3DJgNPcTA0k8gFCaTjkfgiczobZHXvmUSrBYBDKQBynVXAEdgCMqLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-02T14:05:34Z"
    mac: ENC[AES256_GCM,data:I+7sFaJP22Ws1nKi8UzfD9pB9eJH/6nprAgJR2ekOqUg73KJlgeMC+p9hky1ZW3JHy9qVVVmcUAtNlC5REgBb+cE6PbgyPdlf8Os7f1Nzl7Brp9oFpIAGf7NCPsTqwBV1nw1g2nOn/AjCi8+1OVFhd/CF5ur3FOxDf2fb7/hHu0=,iv:TXnCK0j+ICdFvO93KCF+U+ZtzaIVKKrEktUDArqnTR0=,tag:Mzojdu7irnjvlRoToVkFVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
