apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:nQYMypbSL6R0alXPQyt2pA==,iv:SC2BLZxx1iqn6kxW7XrY0Vry48sIFP8oDCtBUU5E4pI=,tag:DY+mHLRBqaw30bSqyICUHw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:KNAam69zjU9sobmELMRty9YTMzlvHkS+/N3Da/uJCUZ2Kk0L,iv:YZjgIM1x26ndBClTOXjV9XhFBR+8uhp4jczUYX7XNKI=,tag:pr4n10iBNl06FfYgf5+D6g==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:tdBjuAJesCj7NbXCFWc=,iv:dC4B8xGdItSwGEGalkJ+W5Sx23CoAXFU1J/u71dIUqw=,tag:28e6/2RZaNQG1fbF9gU/eA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nxcj78klmmh6uxf40musqmvmfayjpfv2sassjcrt22rtjsa4xd3svvtlxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTHhwM2lzZk5hZmx2VDhj
            TnFnd0JONEE5VWdwQmxVSUE0cEprWUhkcEc0ClJxbHlMbUFOUjVrenJ0UTFWeFdn
            Wk5hN1BteFk1bHg4cUE3YXV2MjZjbHcKLS0tIGxSZjJoODlJR0JGWG5JYzZaandU
            dzFRTWN6MGhqZllmN2lwNS9nNTJURXMKxRQS5tpXtY/iFGoOAXjAzCSzje8clZs4
            R9Vx6qf7kPQUFlDuVsCZ7C+lIcx6EvQzRjRcFEmVqNVHKzdhUa3AHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-02T15:03:00Z"
    mac: ENC[AES256_GCM,data:x5+5IP/TpDMM7dUjBSuiJ+72yzkoJy/ZmQ3Ly0zrjDxIpdMiRzMxna4BImju0TQnh060mnlKv0MeSElRscBMYu3aeMIZhQtn2hY5qTfZ/77S6Xvi+h0Y1qVmLPCUP4wUfKvMc9HxvMl0V0gDgZtpmHNBvNmKLCI34O1m/JF5SrI=,iv:A5ZhGQEnSekVATUhlLJ8MkhBEGOXXqORWy7S5H+eIwc=,tag:O8ilkuG1wAx8A2EXNy9bpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
