apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:19SfNg4LINOBJMS1,iv:dm1xPQqO/PCNsOyMM7BcBdu44YxEsDSAnGUoeMuTT0U=,tag:CXfEZGTXr++Pgj+MTzctLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nxcj78klmmh6uxf40musqmvmfayjpfv2sassjcrt22rtjsa4xd3svvtlxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ckZpUUlrb1JLVWNKOEJC
            VFlDU2E4RTlwNGdoM1BoVlZNSFl3czBJUGxVCk5WOThDM1ZSZjV5cXpjd2tKc2g1
            SUNoWW9ZNE9qOVF1TEFEUTRqWFpzTVEKLS0tIFdoMGZqWlBPZEN3TDJrU1dSci9o
            Ynh3WUg3UUVQdy92N0JFRXRpSmhlZGMK7AZlHvti/dUryfFjlKhnu9IevdYSjHaD
            Lpi540MJbm85uGjsQSaLjvrSwMh2QIhPm0ENUk1nLz2RA31abkKqYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-02T14:05:33Z"
    mac: ENC[AES256_GCM,data:fi0povNtwgByXDdS/KxTXUUYsBTtirUeHXG2zyRz7ZKHgSz6VuDEUVZCRqwPK7NTX0cx95nZEPIIlc6LmQ8Pt+eecXdOkRQyarRHrPfFSneUhZ7483CY59IFPUg9xWXh28bIvVOOxVJiThzhwVqo5RbK75n3GTFrMXJfnHB5gnc=,iv:VQHp8oCV6TC2QanCjFjd0FTGJdWWa2K59QvcV2yrMgM=,tag:EC7otsCX6uRv6fYx52eKNA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
