---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
  namespace: argo-system
  # annotations:
  #   argocd.argoproj.io/sync-wave: '0'
  labels:
    argocd.argoproj.io/instance: argo
spec:
  project: default
  sources:
    - repoURL: ghcr.io/argoproj/argo-helm
      chart: argo-cd
      targetRevision: 8.2.4
      helm:
        releaseName: argo-cd
        valueFiles:
          - $repo/kubernetes/apps/argo-system/values.yaml
      #     - $repo/kubernetes/apps/argo-system/argo-cd/values.sops.yaml
    - repoURL: "https://github.com/wouterbouvy/home-ops.git"
      path: kubernetes/apps/argo-system
      targetRevision: main
      ref: repo
  destination:
    name: in-cluster
    namespace: argo-system
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true