apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:gelLuEqPsgLOXOiiR3UlF6aAI5NvNBKW/5PGHMbJp+o3Tw4y,iv:wJYIo8xohPGnQi2tTjCoLJH1UQlDNCWNfYnqbAjot74=,tag:bjgAqsBNRusevuEL7bPucw==,type:str]
    credentials.json: ENC[AES256_GCM,data:kxhHv4416G1XDEBUKN2d+wVCpeDV48elH6ngEsiJAIozMOFB2ATEc7jtEZlQfOvRT30nwLt5HfpSe68fC3aTs+g+FIlX+BOkYLOztPLaj1VDgJFseZ094KEZETrDx6mVZVYSRYqAJTbm1DsvFuZGKq90URiPyKsKrT7JcNmJDWVQ4lnZlOnyBldnP7ZDObc+rT8I4+q8VGVjmGoHT+iSzMs+07tHIrKuuUkuqkZX1g==,iv:E7k+S7+hrBE6LmBKPY4P4rmULhyYaTqcKx5vPIc+X9U=,tag:Hii1Krt/5Fg/9hcprccl6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nxcj78klmmh6uxf40musqmvmfayjpfv2sassjcrt22rtjsa4xd3svvtlxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTzRuVUs3Z2ptSmZ4Rko4
            NHRieG8rVXJaZkEvTTNuY1FxUmVaZVRzM2x3Cis0ZExENjg5TC9WN2xjNXN5TjBR
            NXd3RnZSQm9aRnlmZDVvQ254a1NlaUkKLS0tIHhnVWdDVkE2WGZBV0pBNnhwNnpu
            dStIVTBmb0NxV0E0M2lNbTBSWFltcW8K1vQgJusWV6KDksZDJ5fqExPPoQo3+ncF
            mAv5a1hYsBbt3z+/0bHQ36s0ZNdO5eioYtR/cU9qGgqHgXAfkEf8UQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-02T14:05:34Z"
    mac: ENC[AES256_GCM,data:rrXhQIr+pdiWujf5hzQrqF7GOi2LldTYm+WZmiX/rYbirtfi2aX2hNxF9tQJRmlH3fohTVOjUThX7JX0E1Sl3qn/pGOY+mDcvKT/P2EnkWCXAngutL+Ketgw22Mzivw2NRKTDAK8gTzKrlKSLW/Rbs+y2ntESYgV3z84wAra+bw=,iv:uFlKFeYEn8fV8DiqT1izeNNThzCqBOpSRVeGxzEawWM=,tag:bZCzUdYrQ+lFuVIkaG/8HA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
