apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:DDAMkqzsCBYihwfVsbX6yt8VwH4SkdexnancAbbQ7We4n8Wg,iv:NsfnATkDUPvLEsRszxd+Pf04rvHHAeNeVceoZRLFx9g=,tag:sgsaabxYwKu2c9enNMEWzw==,type:str]
    credentials.json: ENC[AES256_GCM,data:exyb5b59Cqut5GiTYlu+Gxj1XCW1OUqf9ykb/cxN87UOH0JAo4ZGaoqpBjNxExUICTpiWHpVnbut2k6l8c6HdJWDRCLHzrGlp3UspDZ+DsncB4orR2iYLiqlZAwkTZNbGDxhsf/YDmTXKFhE6FwsqiPPPrGO5Em/1HgS1GizDg1VAQ1fznTvBq3TaLp2zZsZQJesiEbFep0yvgUgtTBRiGdgl12UZyQvg/5N6Mh8wg==,iv:ClLw8V3a4uUX/HcNuQVWcvoFt3SR31nPHotmCbD2W6M=,tag:5+2OA6ouIT3ur5FhT056PQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nxcj78klmmh6uxf40musqmvmfayjpfv2sassjcrt22rtjsa4xd3svvtlxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUDZ4OG5pYXhUNDRrc3pR
            QzJySStKV3RaMTBUUzFwQXlhVVE3K3IxS1JJClBIRVFCOGxQcCttbVZPVnJJT3Mz
            TnQzM1cxcnBNSEZGR1c5R000YWdFbjgKLS0tIDNrdzVWZ1hhZnk4K1krYzI0Q1hz
            dEpuMkNZT092bjhyVDdTa2g0WlZzdjgKGdCgBHeGHvZzddEosSsMc6OIC+nHboun
            N49JCE8ck/OoeuRpGhty13YlyVmtwTmfpecWmIGnvVhDcrCL8Ja70Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-02T15:03:00Z"
    mac: ENC[AES256_GCM,data:hurqpr5CHkjB/bc+/+z856xKnkAaIhR4IJfXyz+5Dyygsaq3iya5e+uDqcQRsw9NlFEJ0asiCEOxNCePNADwoi0FXNJ03WSLZvafTbVUTrP0G4ol8+zWhDUpq63WBI5r844FwdJY3OR4/uATFoh5EgVaOd0wdByxociDsq+BhF4=,iv:H5lwFqGsOQfe23oL39R/g35vhYtbUCBsKvmp3xDlu+E=,tag:7bwTa+RIUW/2xGJZXGpNKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
