apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:v4DgkRVr3AI0hF0SU5IC1X53JkxZYj4RiaIcVyGA+Vle8AS3,iv:BAGqikAr3Kb2/m96sH3lfFbTKjYUj0G6bT9uw8669uQ=,tag:esgfLaW1DY3OBvRMXyl7sA==,type:str]
    credentials.json: ENC[AES256_GCM,data:HFo5YKVqT3+3hzviiWNtr6TuPt0Cg5KxMt5XAIKRnPJTqJ3rZWPNHdPHYeBBl+ZPnZpKLCpw0TvxjDaRMPxPQ4E6vPFExkc+NJfIUN7sdQDrqm1A7A9qXfLd3Bqu70P1GJdxJQJ3VDq4Fia93v9SOICjf/RLh37NwPLvZWnTwTI+eb+mWSRYzM8cbk1ngiIg5RbBShDShRe9CyudIr1vwfZ4uR66wD5wOnzwgw6NZQ==,iv:ljvSTZIRpK3TzKlisrkWcf4lL+e8g1a45agEkc2hVb0=,tag:87UAlUGSXmPa24vniuzpOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nxcj78klmmh6uxf40musqmvmfayjpfv2sassjcrt22rtjsa4xd3svvtlxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WU1TbnlPcWlHb1NFdi95
            NXhZUmQ1dEtINERtcmkrWjF6a01aajNXWVU4ClhBMit4ZzJyckVFYkpuekNOR2dw
            eXFEZmY2OEo3d0x5Sy96R25HU1FSQUEKLS0tIHFUMGN2eVplMHFNOG52UlZJNjBn
            dGM1bWR0cUc4TlhBWDFKWCt3ektXY3MKS2pRph2HPi4qc9uP03CvVlZ5/kLdZLSH
            E5bSJq4LOoKo/qOrpOu5MTcQMPr3f4JiqttL2lqClORSMvbGKagkUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-31T09:42:43Z"
    mac: ENC[AES256_GCM,data:8C6FeOafJCRnBM3SN1LwLTBu/DLFGuz5pOuhPP6HvPICHtZ/qiBAi9xJJd+B9Fku+t2JCsSI5eSt7x3Vjre2tCauSX3Gk8CGE3tRGxhi0cqAYW7tGaXWlSEjpYZ4sRPGu4W6nuKBWUto+3CED2LUZayEL/FVh/qPew8jJ43tgsw=,iv:/24OwnCCeY6UZi8t5RdjXYkKiXDG+3UJcfLgjUPnkh4=,tag:mtq0qg/tbpvvdFmmlrOEug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
