apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:FqYvHuS7s6Pdc74F95TNSWQ/9xqEvM6yxfkqgFPTcr4=,iv:+gpTjP2cpRRnCb3Jr7HVP3/ENOdCWlQMSDN184mhZBA=,tag:boY+LQcwUVUtxtuNpInRWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qy5yxmh6g3pg92vjdgd6f3prrdvktsf0szcvjrqmc37nac35tapq8v2r00
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVnZGeldpQ2E2b2Z1aEdO
            Z0oyNkJFTDNJNlFUNnBhTlh1UDdZb3k5LzFZClNMbG11T1dhTGwrdVFCY255RXhk
            cVNpZit4cmJLRUNPaEg2ZDFxSXpxRWcKLS0tIDlRcWhWTjRNMVZKakJmMzI1TTJz
            ZHplMWpxeHJQNDZUNUc1cjZQaFBhcGsKPWVEN4o9wzHEmuBx9VEGsS6q6Nl8CJkM
            TNmL7llad/Qgq+dCeKnLg+1KKZjFZHpu2ycncu+WZUGIpGhX5Qr8gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-14T11:08:46Z"
    mac: ENC[AES256_GCM,data:n1udlsStShfHoeM/5k9m4AOGLp16rIoeJ6JPnUhY9iYZR5CIPVg6jvF1HrpgcmsQlCs0zG/HlYRW1Q6vyC+5FF8TkPkuDAQdJp901B1ULE00v/ECd+Q3RLGct2V2SjRXifJ00IQI6Ssv3qyFSTKiP97CpMtzAapLQ7BMLaijzqI=,iv:pghWdjPs3UynZM+mbbMlXpGaDTdatF3kAp1rn55kPjs=,tag:EFa+MBNkqHXiB2P3YuyUGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
