apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:OYvqJ8IqR+NfPP+iI+SA5XSIhDHIS6gAGCq6RZNfohVQHnA8onpmPg==,iv:dWK8FQTA2spHa89sIWmZeaYvDjswvhDpYRSzyJnF7uk=,tag:3f3nING7Kkhqcr+3SrQevA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qy5yxmh6g3pg92vjdgd6f3prrdvktsf0szcvjrqmc37nac35tapq8v2r00
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSlFwRUNXaGoxMHJFRFpE
            cU0zcTN0d2syVDNTZDRyZkRIby83d2w4ajJ3CkdjZUFrVTRaa1hnR3VKV2h3cXlM
            WDJySmc3ZDhTYS9sNk1QNHlYOUhPS3MKLS0tICtOOVhjVFFHSG5BTmh0ME5hYmN6
            VkpLZ0tualpPMys4VDIxbzlxd29NdGcKInTtr+BWoNpALdwoNh+WpZrlomv+hmcN
            zhq4bS5EwZyhppro9TEEanlYydohPCPR+NFIHmIeNwvvDOiXvVv5Hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-14T11:08:47Z"
    mac: ENC[AES256_GCM,data:JQ99N51PKbj7OC/wYatyBL0KTIdCoIzP717O1BXahwM4iEI5GRRZ9Czk5/+6SuRZbzypJ43+I5IVahApI9WSkdr9mnOiBlUoG103loqiGICLXHv2sli1H/FtYBxmVyclnmU+uSGm+CpVal1wzMOSyFIIImEmhmLgrLlWa2sDiT0=,iv:suBU0LjFzRYGQ0gAfT4nx/MPJeqmL1wQZ7mu7rOu2Rg=,tag:ut56DWCEDnsN/iDxyeltGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
